### ISSUE TITLE
How to get sentence IDs for alignments when using pre-split text?

### ISSUE THREAD

**Issue by jantrienes** [rstodden/TS_annotation_tool#1]
Hi @rstodden, 

Thanks a lot for providing this amazing tool! 

We encountered a problem when annotating sentence alignments for a parallel corpus were documents are pre-split into sentences (`pre_split=True`). We've prepared documents as per the guide in below format and upload with `parallel: True, Pre aligned: False, Manually aligned: False, Pre split: True`.

However, we've noticed in the CSV export `"get alignments for IAA and automatic Alignment"` that all sentences get assigned IDs `<doc_id>-0-0-0` and `<doc_id>-1-0-0` respectively. 

Looking at the implementation, it seems that `Document.add_sentences` is [called N times](https://github.com/rstodden/TS_annotation_tool/blob/51073d2c91148c7155b7a7a9ec0e90352ee1094a/data/models.py#L210) (once for each sentence in the document) and each sentence is again assigned ID 0. As a workaround, we've used following bit of code in place, which works for our use case. 

```py
if pre_split:
    sentences = [nlp(sent.strip().decode("utf-8")) for sent in document_content[1:]]
    number_sentences = len(sentences)
    document_tmp.add_sentences(
        sentences, -1, language_level, selected_license,
        number_sentences, find_most_similiar=find_most_similiar,
        sents_nlp=sents_nlp, nlp=nlp
    )
```

I'm happy about any pointers if this is the right way to go, or if we should prepare the data in a different format. Thanks a lot!

--- 

Document format

```
# © Origin: source_of_data [last accessed: YYYY-MM-DD]\ttitle_of_document
sentence 1
sentence 2
...
sentence N
```

**Comment by rstodden** [comment]
Hi @jantrienes,

Thanks a lot for using the annotation tool and pointing to the issue! 

You're right; the problem is our code and your data format. I assume the error is based on a previous approach which also allowed uploading texts which were pre-split into paragraphs. However, you are correct that we forgot to increase the sentence id, and your workaround looks reasonable. I have updated the code (see [commit #51073d2](https://github.com/rstodden/TS_annotation_tool/commit/51073d2c91148c7155b7a7a9ec0e90352ee1094a) ). I keep the for-loop instead of your suggested list comprehension to still be able to recognize special input formats (e.g., each line starts with a language id and some identifiers).

In the previous version, each input line was again split into sentences with Spacy, which might have led to wrong or at least unintended sentence splittings. With your workaround, this problem is also solved: now, each line is treated as one data point (or one to-align record), regardless of how many sentences might be included in it.

**Comment by jantrienes** [comment]
Hi @rstodden, I tried the latest version (bec650832682117b8a4cdd8b15563361f7b6e4bd) and I can confirm that the issue is resolved. Thanks a lot for your help!
